### PR TITLE
fix: sourcemaps

### PR DESCRIPTION
**Pull request by KingSora**
This is #143 but working, since #143 was so old I couldn't make it work again...

### CODE REVIEW

**Comment by KingSora** [comment]
@madyankin This is working now.. the `snapshot` test fails because I'm on windows and the generated sourcemaps have backslashes `\` as their paths. Thus the `snapshot` also has `\` as the path separator, but your CI runs on `Ubuntu` where normal forward slashes `/` are the path separator... I'm not sure what to do here.. you can remove the snapshot if thats the fastest solution for you

**Comment by madyankin** [comment]
@KingSora got it, I’ll take a look. Meanwhile, could you rebase the branch please?

**Comment by KingSora** [comment]
@madyankin We could fix this by normalizing all the paths from the sourcemap in the test, and then match this normalized version with the snapshot. Is this solution something you would consider or is this too much hassle?

**Comment by madyankin** [comment]
> @madyankin We could fix this by normalizing all the paths from the sourcemap in the test, and then match this normalized version with the snapshot. Is this solution something you would consider or is this too much hassle?

Yeah, that can be a solution. Could you also rebase the branch please?

**Pull request closed without merging**
